services:
  - type: web
    name: morse-trainer
    env: python
    buildCommand: pip install -r requirements.txt && playwright install
    startCommand: python main.py
    envVars:
      - key: PORT
        sync: false

